services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspaces/dev-templates
      - ~/.ssh:/home/dev/.ssh:ro
      - ~/.gitconfig:/home/dev/.gitconfig:ro
    working_dir: /workspaces/dev-templates
    env_file:
      - path: .env
        required: false
    tty: true
    stdin_open: true
